# Generated by Django 3.2.13 on 2022-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15, verbose_name='Name')),
                ('Owner', models.TextField(verbose_name='Owner')),
                ('dateuploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date uploaded')),
                ('Desc', models.TextField(verbose_name='Description')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('image', models.ImageField(upload_to='Images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_item', models.CharField(max_length=50)),
            ],
        ),
    ]
