# Generated by Django 3.2.13 on 2022-08-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='itemstype',
        ),
        migrations.AddField(
            model_name='itemdata',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeapp.itemstype'),
        ),
    ]
